### ISSUE TITLE
openssl when cross compiling

### ISSUE THREAD

**Issue by lxwbr** [rnag/rust.aws-cdk-lambda#11]
It seems that some crates rely on native openssl. Building on my M1 mac I receive an error that the openssl cannot be found. I assume it is because I am building for Linux. Did you encounter this problem and how did you manage to solve it?

**Comment by lxwbr** [comment]
Ok seems like adding this to cargo.toml fixes the issue:
```
openssl = { version = '0.10', features = ["vendored"] }
```

**Comment by rnag** [comment]
@lxwbr assuming this is for the `reqwest` dependency, which is one of the more popular crates, it should be possible to disable the default openssl feature, and enable the `rustls-tls` feature, which uses rust native tls rather than an openssl implementation (which is os dependent and can cause some issues on Linux platforms like AWS Lambda).

For example, in `Cargo.toml`:
```
reqwest = { version = "*", default-features=false, features = ["rustls-tls"] }
```

You can also see usage of this in the `Cargo.toml` in the sample CDK projects, for example:
https://github.com/rnag/rust.aws-cdk-lambda/blob/main/cdk-examples/rust-bins/Cargo.toml#L24

**Comment by lxwbr** [comment]
@rnag it's something more niche where I do not have a real alternative: https://github.com/Keats/jsonwebtoken
